plugins {
    id 'java'
	id 'org.springframework.boot' version '3.3.5'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'checkstyle'

}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}


repositories {
	mavenCentral()

    maven {
        url "https://repo.spring.io/milestone"
    }
}

dependencies {



        implementation 'org.springframework.boot:spring-boot-starter-web'
        // mybatis 의존성과 충돌
//	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
//	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

        
        // .env 파일 사용을 위한 의존성 
        implementation 'me.paulschwarz:spring-dotenv:4.0.0'

        // log4j 의존성 
        implementation 'org.springframework.boot:spring-boot-starter-log4j2'


        //spring securit & OAuth2
        implementation 'org.springframework.boot:spring-boot-starter-security'
        implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'


        // redis 설정
        //lettuce 포함 
        implementation 'org.springframework.boot:spring-boot-starter-data-redis'

        //redis 세션 저장소 설정 
        implementation 'org.springframework.session:spring-session-data-redis'

// https://mvnrepository.com/artifact/junit/junit
testImplementation 'junit:junit:4.13.2'
        // mybatis 설정 
        // https://mvnrepository.com/artifact/org.mybatis/mybatis
        implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'

        runtimeOnly 'com.mysql:mysql-connector-j'


        // swagger를 위한 openapi
        implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'

        /* NATS + JetStream 지원 */
        implementation 'io.nats:jnats:2.17.6'

        // openai 설정
        implementation platform("org.springframework.ai:spring-ai-bom:1.0.0-M5")
        implementation 'org.springframework.ai:spring-ai-openai'

         /* JSON 직렬화 */
        implementation 'com.google.code.gson:gson:2.10.1'


        /* test */
        // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test
        testImplementation 'org.springframework.boot:spring-boot-starter-test:4.0.0'
        // https://mvnrepository.com/artifact/junit/junit
        testImplementation 'junit:junit:4.13.2'
}

// log4j를 사용하기위해 logback 비활성화
configurations {
    all {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}


sourceSets {
    test {
        java {
            srcDirs = ['src/test/java']
        }
    }
}





tasks.named('test') {
	useJUnitPlatform()
}


